default: &default
  adapter: postgresql
  encoding: unicode
  host: users-db
  username: postgres
  pool: 5

development:
  <<: *default
  database: users-ms_development


test:
  <<: *default
  database: users-ms_test
